[package]
name = "cheatbook014"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14.0-rc.2" }
# bevy = { git = "https://github.com/bevyengine/bevy" }

[dev-dependencies]
image = "0.25"
winit = "0.30"

# [[bin]]
# name = "input-char"
# path = "src/input/char.rs"
